### ISSUE TITLE
Multiple touches for big buttons on mobile version to work

### ISSUE THREAD

**Issue by PhyroPhyro** [DexterHuang/CyberCodeOnline#437]
Hello,

I don't know if this is intentional, but big buttons on mobile version, such as the completed quests and travel locations ones, requires more than one touch to execute, or a longer touch. It slows down the experience quite a bit and keeps me away from the mobile one, even when it's more convenient.

**Comment by DexterHuang** [comment]
hello @PhyroPhyro  :) I have deployed a patch for this, but I cannot be sure if it fixed the issue,
could you help restart the app and see if the issue has been resolved?

**Comment by PhyroPhyro** [comment]
I restarted it and I still have to touch twice sometimes. Sometimes it just animate the press but don't execute it. I feel that if I do a long press, it gets more reliable. I'm using a Samsung Galaxy S10+, btw

**Comment by JEricaM** [comment]
I confirm the same problem. Sometimes I need to press twice on big buttons.
device Honor p9 lite with Android 9

**Comment by DexterHuang** [comment]
When was last time happened? I have pushed a patch for this a few days ago

**Comment by JEricaM** [comment]
Happened now, Android 9 , device honor p9 lite
The "problem" appears sometimes when I travel.
The app it's updated

**Comment by PhyroPhyro** [comment]
Playing now in an OnePlus 8T and still having the same issue in the same buttons. App is indeed updated as well.

**Comment by tripplehelix** [comment]
I have had this issue too, Oneplus 6 running LineageOS... Seems to just ignore inputs sometimes.

**Comment by tripplehelix** [comment]
I have moved this to the bug spreadsheet
https://docs.google.com/spreadsheets/d/1cudIpT0gKAL48MgIaG22cSkj6jySpwxJ8zqboekG5K8/edit?usp=sharing
