### ISSUE TITLE
Shielded enemy in dungeon

### ISSUE THREAD

**Issue by jnlcode** [DexterHuang/CyberCodeOnline#59]
Shielded enemies in dungeon do not have the shield effect. Once the player hits the enemy, the shield disappears and their main hit points take as much damage as if they were unshielded. This only happens to shielded enemies in dungeons and not in nearby enemies.

--avexx

v0.58

**Comment by DexterHuang** [comment]
is it possible that is just your damage is so high it destroys their shield in one hit?

**Comment by jnlcode** [comment]
This is the link to see the bug in action. It only happens in dungeons. My damage is 6480 but I end up causing total of 5266 (shields) + 6480 (damage to HP) to the enemy.

[https://imgur.com/a/QuoVlPd](url)

**Comment by DexterHuang** [comment]
ah! thanks 👍

**Comment by DexterHuang** [comment]
fixed :)

**Comment by jnlcode** [comment]
I'm still encountering the bug and have a good idea now of what causes it. 

If the first attack is greater than the enemy's shield, then the shield is destroyed and the health also gets hit by the full amount of damage. 

If the first attack is less than the enemy's shield, then the shield will absorb the damage and the health is untouched.

Hope this helps to narrow down where the bug in the code is.

**Comment by DexterHuang** [comment]
hmmm I know what you mean, I have checked the code that could cause this kinda issue many times, the logic seems fine...
i have change it up abit, can you see if it still happen to you?

**Comment by levi-middleton** [comment]
This still occurs in dungeons. As an example, I attacked a shielded murderer (192 shield, 342 health) with my primary weapon (360 damage). The following message appeared in system log: "[system]: You attacked Shielded murderer, dealing 349 damage." The enemy was dead after that single attack.

**Comment by DexterHuang** [comment]
Hmmm and you are positive that there is no one in the dungeon with you and happen to attack the murderer at same time? 🤔

This is really weird...

**Comment by levi-middleton** [comment]
Yes, I was alone in the dungeon.

**Comment by tripplehelix** [comment]
Pretty sure this is fixed now
